//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hm_SqlInEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueBooks
    {
        public int IssueId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string ReaderName { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
